#!/bin/sh
set -e

case "$1" in
    install|configure)
        exampleConfig="/var/lib/linuxmuster-cachingserver/server.json.example"
        realConfig="/var/lib/linuxmuster-cachingserver/server.json"

        if [ ! -f $realConfig ]; then
            cp $exampleConfig $realConfig
        fi

        exampleConfig="/etc/linuxmuster-cachingserver/config.json.example"
        realConfig="/etc/linuxmuster-cachingserver/config.json"

        if [ ! -f $realConfig ]; then
            cp $exampleConfig $realConfig
        fi

        systemctl stop isc-dhcp-server
        systemctl disable isc-dhcp-server

        mkdir -p /var/log/linuxmuster/cachingserver/

        systemctl enable linuxmuster-cachingserver-satellite
        systemctl start linuxmuster-cachingserver-satellite

        exit 0
        ;;
    upgrade|abort-upgrade)
        echo "No work to do..."
        exit 0
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
