#!/bin/sh
set -e

case "$1" in
    install|configure)
        exampleConfig="/var/lib/linuxmuster-cachingserver/server.json.example"
        realConfig="/var/lib/linuxmuster-cachingserver/server.json"

        if [ ! -f $realConfig ]; then
            cp $exampleConfig $realConfig
        fi

        systemctl stop isc-dhcp-server

        mkdir -p /var/log/linuxmuster/cachingserver/
        mkdir -p /etc/dhcp/devices

        systemctl enable linuxmuster-cachingserver-api
        systemctl enable tftpd-hpa
        systemctl enable rsync
        systemctl enable isc-dhcp-server

        pip3 install fastapi -U
        pip3 install uvicorn
        pip3 install jc

        python3 /usr/share/linuxmuster-cachingserver-satellite/migrate-server-secret.py

        systemctl restart tftpd-hpa
        systemctl restart rsync
        systemctl restart cron
        systemctl restart linuxmuster-cachingserver-api

        exit 0
        ;;
    upgrade|abort-upgrade)
        echo "No work to do..."
        exit 0
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
